version: '3'
services:
  db:
    container_name: sentry-postgres
    image: postgres
    env_file:
      - ./envs/psql.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - '5432'
  redis:
    container_name: sentry-redis
    image: redis
    volumes:
      - redis-data:/data
    expose:
      - '6379'
  sentry-cron:
    container_name: sentry-cron
    image: sentry
    command: run cron
    env_file:
      - ./envs/sentry.env
    depends_on:
      - db
      - redis
  sentry-worker:
    container_name: sentry-worker
    image: sentry
    command: run worker
    env_file:
      - ./envs/sentry.env
    depends_on:
      - db
      - redis
  sentry:
    container_name: sentry
    image: sentry
    env_file:
      - ./envs/sentry.env
    ports:
      - '9000:9000'
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
volumes:
  pg-data:
  redis-data:
